// Generated by CoffeeScript 1.6.2
(function() {
  var buildFile, buildIncludes, config, copyRequire, copySourceMap, deleteFile, fs, getModuleId, getOutputFile, log, np, utility, watcher;

  utility = require("glass-platform/node/build/utility");

  watcher = require("glass-platform/node/build/watcher");

  np = require("path");

  fs = require('fs');

  config = {
    input: {
      directory: "node",
      exclude: "node_modules"
    },
    output: {
      directory: "browser",
      name: "glass"
    }
  };

  log = function(config, message) {
    if (!config.silent) {
      return console.log(message);
    }
  };

  getModuleId = function(config, file) {
    var path;

    path = np.relative(config.input.directory, file);
    path = path.replace(/\\/g, "\/");
    path = path.replace(/\bindex\.js$/, "");
    path = config.output.name + "/" + path;
    path = path.replace(/\/$/, "");
    return path = path.replace(/\.js$/, "");
  };

  getOutputFile = function(config, file) {
    var path;

    path = np.relative(config.input.directory, file);
    path = path.replace(/\\/g, "\/");
    path = config.output.name + "/" + path;
    return path = np.join(config.output.directory, path);
  };

  deleteFile = function(file) {
    if (fs.existsSync(file)) {
      return fs.unlinkSync(file);
    }
  };

  copySourceMap = function(config, inputFile, outputFile, deleteOutput) {
    var copyTo, index, map, mapInput, mapOutput, shortName, source, _i, _len, _ref;

    if (deleteOutput == null) {
      deleteOutput = false;
    }
    mapInput = inputFile.replace(/\.js$/, ".map");
    mapOutput = outputFile.replace(/\.js$/, ".map");
    if (fs.existsSync(mapInput)) {
      map = JSON.parse(utility.read(mapInput));
      _ref = map.sources;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        source = _ref[index];
        source = np.join(np.dirname(mapInput), map.sourceRoot, source);
        copyTo = np.join(np.dirname(mapOutput), shortName = source.split(/[\/\\]/g).pop());
        if (deleteOutput) {
          deleteFile(copyTo);
        } else {
          if (!fs.existsSync(source)) {
            console.warn("Source not found: " + mapInput + " -> " + source);
            continue;
          }
          utility.copy(source, copyTo);
        }
        map.sources[index] = shortName;
      }
      map.sourceRoot = ".";
      if (deleteOutput) {
        deleteFile(mapInput);
        return deleteFile(mapOutput);
      } else {
        return utility.write(mapOutput, JSON.stringify(map, null, '    '));
      }
    }
  };

  buildFile = function(config, file) {
    var id, input, output, outputFile;

    outputFile = getOutputFile(config, file);
    if (!fs.existsSync(file)) {
      copySourceMap(config, file, outputFile, true);
      deleteFile(outputFile);
      return;
    }
    id = getModuleId(config, file);
    input = utility.read(file);
    output = "(function(){require.register('" + id + "',function(module,exports,require){" + input + "\n})})()";
    utility.write(outputFile, output);
    log(config, "Wrapped " + outputFile);
    if (config.output.debug) {
      return copySourceMap(config, file, outputFile);
    }
  };

  buildIncludes = function(config) {
    var base, file, includeFile, list, script, _i, _len, _ref;

    if (config.output.include == null) {
      return;
    }
    list = utility.list(config.output.directory, {
      include: ".js",
      exclude: [config.output.include.name, "require.js"]
    });
    list = list.map(function(x) {
      return np.relative(config.output.directory, x).replace(/\\/g, '\/');
    });
    list = list.sort(function(a, b) {
      return a.length - b.length;
    });
    script = "";
    base = (_ref = config.output.include.base) != null ? _ref : "";
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      file = list[_i];
      script += "document.writeln(\"<script src='" + base + file + "'></script>\");\n";
    }
    includeFile = np.join(config.output.directory, config.output.include.name);
    utility.write(includeFile, script);
    return log(config, "Created " + includeFile);
  };

  copyRequire = function(config) {
    var source, target;

    source = np.join(__dirname, '../browser/require.js');
    target = np.join(config.output.directory, 'require.js');
    if (!fs.existsSync(target)) {
      utility.copy(source, target);
      return log(config, "Copied " + target);
    }
  };

  exports.build = function(config, callback) {
    var file, list, _i, _len;

    list = utility.list(config.input.directory, {
      include: ".js"
    });
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      file = list[_i];
      buildFile(config, file);
    }
    buildIncludes(config);
    copyRequire(config);
    return typeof callback === "function" ? callback() : void 0;
  };

  exports.watch = function(config) {
    buildIncludes(config);
    copyRequire(config);
    return watcher.watchDirectory(config.input.directory, {
      include: ".js",
      initial: false
    }, function(file, curr, prev, change) {
      buildFile(config, file);
      if (change === "deleted" || change === "created") {
        return buildIncludes(config);
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
