// Generated by CoffeeScript 1.6.2
(function() {
  var assert, r;

  if (typeof describe === 'function') {
    assert = require('assert');
    r = require('../www/require');
    describe('require', function() {
      return describe('normalize', function() {
        return it("glass/index + ./global should be glass.global", function() {
          return assert.equal("glass/global", r.normalize("glass/index", "./global"));
        });
      });
    });
  }

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
